name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build changelog
        id: github_changelog
        run: |
          changelog=$(git log $(git tag | tail -2 | head -1)..HEAD --no-merges --oneline)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.github_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build-package:
    name: Build binaries
    needs: create-release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --extra build

      - name: Build artifacts
        run: |
          cd src
          uv run python build_package.py

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/flaresolverr_*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
